# Site settings
title: Glaubenskurs
email:
description: >
  Unsere Glaubenskurs‐Wochenenden bieten jungen Christen die Gelegenheit, mehr über den katholischen Glauben und seine Bedeutung für ihr Leben zu erfahren und sich darüber mit anderen Jugendlichen und jungen Erwachsenen auszutauschen. Natürlich kommen auch Gebet und Spiel & Spaß nicht zu kurz. Gemeinschaftsprojekt von Schönstatt MJF, OMI-Jugend, Schönstatt-Mannesjungend und Katholische Jugend im Bistum Fulda.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://glaubenskurs.bonifati.us" # the base hostname & protocol for your site

permalinks: pretty
top_nav:
  - kurse

# Page settings
collections:
  kurse:
    output: true
    permalink: /:collection/:path/

defaults:
  -
    scope:
      path: ""
      type: pages
    values:
      show_nav: true
      sitemap:
        lastmod: 2015-08-16T14:28:40+00:00
  -
    scope:
      path: ""
      type: kurse
    values:
      cover: cover.jpg
      layout: event
      published: true
      sitemap:
        lastmod: 2015-08-16T14:28:40+00:00

markdown: kramdown

asciidoctor:
  attributes:
    - idseparator=_
    - source-highlighter=coderay
    - icons=font-awesome

exclude:
  - 'Rakefile'

gems:
  - algoliasearch-jekyll

# Server settings
port: 4000
host: 0.0.0.0

flickr:
  api_key: '6e1fe3de2ea7c8e46c6e139b9f351e30'
  shared_secret: 'd0975b5005bc9500'

markdown_ext: adoc

algolia:
  application_id: 'E7UT30N10W'
  index_name:     'glaubenskurs.bonifati.us'
  excluded_files:
    - googlebaf10e1859ea12e7.html
    - 404.html
    - impressum.html
    - datenschutz.html
  settings:
    attributesToIndex:
      - title
      - themen.title
      - themen.referent
      - unordered(themen.tags)
      - h1
      - h2
      - h3
      - h4
      - h5
      - h6
      - unordered(text)
      - unordered(tags)
      - ort
    attributesForFaceting:
      - type
      - title
      - themen.tags
      - themen.referent
      - ort


# settings for deployment (Rakefile)
git:
  repo: git@github.com:Bonifatius/glaubenskurs.git
  branch: gh-pages
