---
title: Glaubenskurs August 2012
ort: dietershausen
beginn: 2012-08-19
ende: 2012-08-21
cover: false
facebook: 234158320036898
themen:
  - titel: "Das Zweite Vatikanum: Was ist ein Konzil und was ist am letzten Konzil geschehen?"
    referent: "Kaplan Dirk Gärtner"
  - titel: "Der Heilige Geist: Wie kann ich ihn mir vorstellen? Wie sein Wirken erkennen?"
    referent: "Pater Thomas Jocheim ISch"
---

Die Schönstatt Bewegung Mädchen und Junge Frauen (MJF), die Schönstatt-Mannesjugend (SMJ), das Jugendbüro der Hünfelder Oblaten (OMI) und die Katholische Jugend im Bistum Fulda (KJF) bieten vom 17.-19. August 2012das vierte Glaubenswochenende für Jugendliche ab 16 Jahren an. Eingeladen sind alle, die sich tiefer mit ihrem Glauben auseinandersetzen wollen, die mehr wissen und verstehen und mit Gleichaltrigen darüber ins Gespräch kommen möchten. Natürlich kommen auch Gebet und Spiel & Spaß nicht zu kurz!

== Programm
Thematisch geht es dieses Mal um den Heiligen Geist. Wie kann ich ihn mir vorstellen? Wie kann ich sein Wirken erkennen? Dann wollen wir uns damit beschäftigen, was eigentlich ein Konzil ist, und was das letzte Konzil, das II. Vatikanische Konzil, vor 50 Jahren an Neuem gebracht hat. Es geht auch hier um den Hl. Geist: Wie wirkt er eigentlich in der Kirche?

Natürlich werdet ihr auch wieder Gelegenheit haben, alle anderen Fragen loszuwerden, und natürlich gibt es wieder die bewährte Mischung aus Themen und Gespräch, Gebet, Spiel & Spaß, Aktionen drinnen und draußen. Wir freuen uns auf Dich!

Geleitet wird das Wochenende von einem ehrenamtlichen Team aus Schönstattjugend, KJF und OMI-Jugend zusammen mit Kaplan Florian Böth. Als Referenten sind Bischofssekretär Dirk Gärtner und der Schönstattpater Thomas Jochheim eingeladen.

== Anmeldung
Die Anmeldung läuft über das KJF-Büro im Bischöflichen Jugendamt, entweder per Mail an bja@bistum-fulda.de oder per Telefon 0661/87367
